NUCLEOTIDES = {'A', 'C', 'T', 'G'}
MUTATION_TYPES = ['S']
PROPORTIONAL_MUTATION_TYPES = ['S']*100  

DEFAULT_MIN_MOTIF_SIZE = 3
DEFAULT_MAX_MOTIF_SIZE = 10
DEFAULT_MIN_REPEAT_LENGTH = 50
DEFAULT_MAX_REPEAT_LENGTH = 200
DEFAULT_NO_FRAGMENT_FRACTION = 0.2
DEFAULT_PURITY = 0.90